In [32]:
import numpy as np 
import pandas as pd 
import seaborn as sns 
import matplotlib.pyplot as plt
%matplotlib inline 
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.linear_model import LinearRegression
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import r2_score
from sklearn.tree import DecisionTreeRegressor
from sklearn.ensemble import RandomForestRegressor
from sklearn.neighbors import KNeighborsRegressor

In [33]:
import warnings 
warnings.filterwarnings('ignore')

In [15]:
akshay=pd.read_csv("C:\\Users\\aksha\\Downloads\\Student_Performance.csv")
akshay

Hours Studied  Previous Scores Extracurricular Activities  Sleep Hours  \
0               7.0             99.0                        Yes          9.0   
1               4.0             82.0                         No          4.0   
2               8.0             51.0                        Yes          7.0   
3               5.0             52.0                        Yes          5.0   
4               7.0             75.0                         No          8.0   
...             ...              ...                        ...          ...   
9995            1.0             49.0                        Yes          4.0   
9996            7.0             64.0                        Yes          8.0   
9997            6.0             83.0                        Yes          8.0   
9998            9.0             97.0                        Yes          7.0   
9999            7.0             74.0                         No          8.0   

      Sample Question Papers Practiced  Performance Index  
0                                  1.0                 91  
1                                  2.0                 65  
2                                  2.0                 45  
3                                  2.0                 36  
4                                  5.0                 66  
...                                ...                ...  
9995                               2.0                 23  
9996                               5.0                 58  
9997                               5.0                 74  
9998                               0.0                 95  
9999                               1.0                 64  

[10000 rows x 6 columns]

In [16]:
akshay.columns

Index(['Hours Studied', 'Previous Scores', 'Extracurricular Activities',
       'Sleep Hours', 'Sample Question Papers Practiced', 'Performance Index'],
      dtype='object')

In [17]:
akshay.shape

(10000, 6)

In [18]:
akshay.size

60000

In [19]:
akshay.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10000 entries, 0 to 9999
Data columns (total 6 columns):
 #   Column                            Non-Null Count  Dtype  
---  ------                            --------------  -----  
 0   Hours Studied                     9998 non-null   float64
 1   Previous Scores                   9995 non-null   float64
 2   Extracurricular Activities        9991 non-null   object 
 3   Sleep Hours                       9992 non-null   float64
 4   Sample Question Papers Practiced  9994 non-null   float64
 5   Performance Index                 10000 non-null  int64  
dtypes: float64(4), int64(1), object(1)
memory usage: 468.9+ KB


In [8]:
akshay.dtypes

Hours Studied                       float64
Previous Scores                     float64
Extracurricular Activities           object
Sleep Hours                         float64
Sample Question Papers Practiced    float64
Performance Index                     int64
dtype: object

In [20]:
akshay.isnull().sum()

Hours Studied                       2
Previous Scores                     5
Extracurricular Activities          9
Sleep Hours                         8
Sample Question Papers Practiced    6
Performance Index                   0
dtype: int64

In [21]:
akshay.duplicated().sum()

127

In [24]:
s=akshay.fillna(0.0)
s

Hours Studied  Previous Scores Extracurricular Activities  Sleep Hours  \
0               7.0             99.0                        Yes          9.0   
1               4.0             82.0                         No          4.0   
2               8.0             51.0                        Yes          7.0   
3               5.0             52.0                        Yes          5.0   
4               7.0             75.0                         No          8.0   
...             ...              ...                        ...          ...   
9995            1.0             49.0                        Yes          4.0   
9996            7.0             64.0                        Yes          8.0   
9997            6.0             83.0                        Yes          8.0   
9998            9.0             97.0                        Yes          7.0   
9999            7.0             74.0                         No          8.0   

      Sample Question Papers Practiced  Performance Index  
0                                  1.0                 91  
1                                  2.0                 65  
2                                  2.0                 45  
3                                  2.0                 36  
4                                  5.0                 66  
...                                ...                ...  
9995                               2.0                 23  
9996                               5.0                 58  
9997                               5.0                 74  
9998                               0.0                 95  
9999                               1.0                 64  

[10000 rows x 6 columns]

In [26]:
s=akshay.fillna(method='ffill')
s

Hours Studied  Previous Scores Extracurricular Activities  Sleep Hours  \
0               7.0             99.0                        Yes          9.0   
1               4.0             82.0                         No          4.0   
2               8.0             51.0                        Yes          7.0   
3               5.0             52.0                        Yes          5.0   
4               7.0             75.0                         No          8.0   
...             ...              ...                        ...          ...   
9995            1.0             49.0                        Yes          4.0   
9996            7.0             64.0                        Yes          8.0   
9997            6.0             83.0                        Yes          8.0   
9998            9.0             97.0                        Yes          7.0   
9999            7.0             74.0                         No          8.0   

      Sample Question Papers Practiced  Performance Index  
0                                  1.0                 91  
1                                  2.0                 65  
2                                  2.0                 45  
3                                  2.0                 36  
4                                  5.0                 66  
...                                ...                ...  
9995                               2.0                 23  
9996                               5.0                 58  
9997                               5.0                 74  
9998                               0.0                 95  
9999                               1.0                 64  

[10000 rows x 6 columns]

In [27]:
s.isnull().sum()

Hours Studied                       0
Previous Scores                     0
Extracurricular Activities          0
Sleep Hours                         0
Sample Question Papers Practiced    0
Performance Index                   0
dtype: int64

In [29]:
s.drop_duplicates(inplace=True)
s

Hours Studied  Previous Scores Extracurricular Activities  Sleep Hours  \
0               7.0             99.0                        Yes          9.0   
1               4.0             82.0                         No          4.0   
2               8.0             51.0                        Yes          7.0   
3               5.0             52.0                        Yes          5.0   
4               7.0             75.0                         No          8.0   
...             ...              ...                        ...          ...   
9995            1.0             49.0                        Yes          4.0   
9996            7.0             64.0                        Yes          8.0   
9997            6.0             83.0                        Yes          8.0   
9998            9.0             97.0                        Yes          7.0   
9999            7.0             74.0                         No          8.0   

      Sample Question Papers Practiced  Performance Index  
0                                  1.0                 91  
1                                  2.0                 65  
2                                  2.0                 45  
3                                  2.0                 36  
4                                  5.0                 66  
...                                ...                ...  
9995                               2.0                 23  
9996                               5.0                 58  
9997                               5.0                 74  
9998                               0.0                 95  
9999                               1.0                 64  

[9873 rows x 6 columns]

In [31]:
s.shape

(9873, 6)

In [34]:
from sklearn.preprocessing import LabelEncoder
le =  LabelEncoder()
s["Extracurricular Activities"] = le.fit_transform(s["Extracurricular Activities"])

In [35]:
s

Hours Studied  Previous Scores  Extracurricular Activities  Sleep Hours  \
0               7.0             99.0                           1          9.0   
1               4.0             82.0                           0          4.0   
2               8.0             51.0                           1          7.0   
3               5.0             52.0                           1          5.0   
4               7.0             75.0                           0          8.0   
...             ...              ...                         ...          ...   
9995            1.0             49.0                           1          4.0   
9996            7.0             64.0                           1          8.0   
9997            6.0             83.0                           1          8.0   
9998            9.0             97.0                           1          7.0   
9999            7.0             74.0                           0          8.0   

      Sample Question Papers Practiced  Performance Index  
0                                  1.0                 91  
1                                  2.0                 65  
2                                  2.0                 45  
3                                  2.0                 36  
4                                  5.0                 66  
...                                ...                ...  
9995                               2.0                 23  
9996                               5.0                 58  
9997                               5.0                 74  
9998                               0.0                 95  
9999                               1.0                 64  

[9873 rows x 6 columns]

In [36]:
x = s.iloc[:,:-1].values
y = s.iloc[:,-1].values

In [37]:
x

array([[ 7., 99.,  1.,  9.,  1.],
       [ 4., 82.,  0.,  4.,  2.],
       [ 8., 51.,  1.,  7.,  2.],
       ...,
       [ 6., 83.,  1.,  8.,  5.],
       [ 9., 97.,  1.,  7.,  0.],
       [ 7., 74.,  0.,  8.,  1.]])

In [38]:
y

array([91, 65, 45, ..., 74, 95, 64], dtype=int64)

In [39]:
from sklearn.model_selection import train_test_split
x_train, x_test, y_train, y_test = train_test_split(x, y, train_size = 0.80,test_size=0.20,random_state=450)

In [40]:
x_train

array([[ 1., 56.,  0.,  6.,  2.],
       [ 8., 51.,  0.,  8.,  4.],
       [ 9., 95.,  1.,  6.,  7.],
       ...,
       [ 5., 50.,  0.,  4.,  8.],
       [ 3., 97.,  0.,  9.,  9.],
       [ 4., 51.,  1.,  8.,  0.]])

In [41]:
y_train

array([31, 47, 94, ..., 36, 76, 28], dtype=int64)

In [42]:
LR = LinearRegression()
LOR = LogisticRegression()
DTR = DecisionTreeRegressor()
RFR = RandomForestRegressor()
KNR = KNeighborsRegressor()

In [43]:
models = [LR , LOR , DTR , RFR , KNR]
for model in models:
    model.fit(x_train,y_train)
    y_pred = model.predict(x_test)
    print(model,":",r2_score(y_test,y_pred)*100)

LinearRegression() : 98.8255071854289
LogisticRegression() : 25.405051250182108
DecisionTreeRegressor() : 97.39820174862058
RandomForestRegressor() : 98.42325927857716
KNeighborsRegressor() : 98.23954084515162
